/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseTestRouteImport } from './routes/supabase-test'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAddInvoiceRouteImport } from './routes/api/add-invoice'

const SupabaseTestRoute = SupabaseTestRouteImport.update({
  id: '/supabase-test',
  path: '/supabase-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddInvoiceRoute = ApiAddInvoiceRouteImport.update({
  id: '/api/add-invoice',
  path: '/api/add-invoice',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/api/add-invoice': typeof ApiAddInvoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/api/add-invoice': typeof ApiAddInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/supabase-test': typeof SupabaseTestRoute
  '/api/add-invoice': typeof ApiAddInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/supabase-test' | '/api/add-invoice'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/supabase-test' | '/api/add-invoice'
  id: '__root__' | '/' | '/about' | '/supabase-test' | '/api/add-invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SupabaseTestRoute: typeof SupabaseTestRoute
  ApiAddInvoiceRoute: typeof ApiAddInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase-test': {
      id: '/supabase-test'
      path: '/supabase-test'
      fullPath: '/supabase-test'
      preLoaderRoute: typeof SupabaseTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/add-invoice': {
      id: '/api/add-invoice'
      path: '/api/add-invoice'
      fullPath: '/api/add-invoice'
      preLoaderRoute: typeof ApiAddInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SupabaseTestRoute: SupabaseTestRoute,
  ApiAddInvoiceRoute: ApiAddInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
